# Generated by Django 6.0.1 on 2026-01-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0002_remove_product_image_alter_product_price_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductMedia",
            new_name="ProductImage",
        ),
    ]
