# Generated by Django 6.0.1 on 2026-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0004_alter_productfeatures_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("lexus", "Lexus"),
                    ("mercedes_benz", "Mercedes Benz"),
                    ("rolls_royce", "Rolls Royce"),
                    ("Bmw", "BMW"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
    ]
