# Generated by Django 6.0.1 on 2026-01-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0005_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="productfeatures",
            name="label",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="productfeatures",
            name="value",
            field=models.CharField(max_length=30),
        ),
    ]
