# Generated by Django 6.0.1 on 2026-01-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0006_alter_product_price_alter_product_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("lexus", "Lexus"),
                    ("mercedes_benz", "Mercedes Benz"),
                    ("rolls_royce", "Rolls Royce"),
                    ("bmw", "BMW"),
                    ("bentley", "Bentley"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
    ]
