# Generated by Django 6.0.1 on 2026-01-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0007_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfeatures",
            name="value",
            field=models.CharField(max_length=60),
        ),
    ]
